name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: "Unit tests (PHP ${{ matrix.php }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: composer
          coverage: xdebug

      - run: composer install

      - run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-filter=src tests/

      - uses: coverallsapp/github-action@v2
        with:
          files: coverage.xml
          flag-name: php-${{ matrix.php }}
          parallel: true

  symfony-tests:
    needs: unit-tests
    name: "Symfony compatibility tests (PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        symfony:  # We only test LTS versions + all versions of current major branch
          - '6.4'
          - '7.4'
          - '8.0'
        exclude:
          - symfony: '8.0'
            php: '8.2'
          - symfony: '8.0'
            php: '8.3'

    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: composer
          coverage: xdebug

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v9

      - env:
          SYMFONY_VERSION: ${{ matrix.symfony }}
        run: |
          GIT_BRANCH_NAME="${{ steps.branch-names.outputs.current_branch }}" bash test-symfony

  code-coverage:
    name: Code coverage
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
